# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sign',
            field=models.BooleanField(default=False),
        ),
    ]
